- name: paimoe pc
  hosts: localhost
  become: true

  tasks:
    - name: install regular software from apt
      apt:
        name: "{{ item }}"
        state: present # this means install if not present, but DO NOT upgrade if present
      loop:
        - git
        - htop
        - curl

    - name: install snaps
      community.general.snap:
        name:
          - spotify
          - upnote
          - hugo
          - vlc

    - name: install homebrews
      become: false
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - gh
        - tree
        - go-task
        - exercism
        - cloc # count lines of code

    - name: install uv
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      become: false
      args:
        creates: /home/paimoe/.local/bin/uv
      register: uv_install

    - name: install zed for simple text editing
      shell: curl -f https://zed.dev/install.sh | sh
      become: false
      args:
        creates: /home/paimoe/.local/bin/zed
      register: zed_install
