services:
  trilium:
    image: triliumnext/trilium:latest
    restart: unless-stopped
    ports:
      - "192.168.0.174:11000:8080"
    environment:
      TZ: Australia/Perth
      USER_UID: "1000"
      USER_GID: "1000"
    volumes:
      - /srv/trilium/data:/home/node/trilium-data
      - /etc/localtime:/etc/localtime:ro
